import type { PromptContext, PromptPart, PromptReference, PromptTextOptions, PromptContextPort } from './types.js';
export type * from './types.js';
export declare function validatePromptReference(reference: unknown): PromptReference;
export declare function validatePromptContext(context: unknown): PromptContext;
export declare function createPromptContext(parts: readonly PromptPart[], operationId?: string): PromptContext;
export declare function referencePart(reference: PromptReference, id?: string): Extract<PromptPart, { kind: 'reference' }>;
export declare function textPart(text: string, id?: string): Extract<PromptPart, { kind: 'text' }>;
export declare function formatPromptReference(reference: PromptReference, options?: PromptTextOptions): string;
export declare function formatPromptContextText(context: PromptContext, options?: PromptTextOptions): string;
export declare const unavailablePromptContext: PromptContextPort;
