// The robot payloads cadgen resolved for this folder's fixture descriptions (`../__fixtures__`,
// regenerated by its `make_fixtures.py` and held current by the Python suite), as the robot
// renderer loads them, and their meshes as the page's loaders would hand them back (a box per
// primitive URL, in millimetres: no mesh is fetched).
import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { buildRobotParts } from "@text-to-cad/core/lib/urdf/robotParts.js";

// Under vitest's jsdom environment a module's URL is served over http from the package root
// (or under `/@fs/` by its absolute path); under node it is a file URL.
function localPath(url) {
  if (url.protocol === "file:") return fileURLToPath(url);
  const pathname = decodeURIComponent(url.pathname);
  return pathname.startsWith("/@fs/") ? pathname.slice("/@fs".length) : path.join(process.cwd(), pathname);
}
const FIXTURES = localPath(new URL("../__fixtures__/", import.meta.url));

/** A fixture file's bytes, by its path under `__fixtures__`: `fixtureBytes("meshes/head.glb")`. */
export function fixtureBytes(relative) {
  return readFileSync(path.join(FIXTURES, relative));
}

/** The GLB a payload's mesh URL names (`/meshes/<file>` or `/primitives/<hash>.glb`, under any prefix). */
export function fixtureGlb(url) {
  return fixtureBytes(String(url).replace(/^.*\/(primitives|meshes)\//, "$1/"));
}

/** `GET /__cad/robot`'s answer for a fixture description: `fixturePayload("arm.srdf")`. */
export function fixturePayload(name) {
  const [stem, kind] = [name.slice(0, name.lastIndexOf(".")), name.slice(name.lastIndexOf(".") + 1)];
  return JSON.parse(readFileSync(path.join(FIXTURES, `${stem}.${kind}.robot.json`), "utf8"));
}

/** What cadgen refuses a refused fixture with (`refusals.json`). */
export function fixtureRefusal(name) {
  return JSON.parse(readFileSync(path.join(FIXTURES, "refusals.json"), "utf8"))[name];
}

/** A box mesh as the page's loaders hand one back, in millimetres. */
export function boxMesh([sx, sy, sz], { colors = null, parts = [] } = {}) {
  const [hx, hy, hz] = [sx / 2, sy / 2, sz / 2];
  const corners = [[-hx, -hy, -hz], [hx, -hy, -hz], [hx, hy, -hz], [-hx, hy, -hz], [-hx, -hy, hz], [hx, -hy, hz], [hx, hy, hz], [-hx, hy, hz]];
  const faces = [[0, 2, 1, 0, 3, 2], [4, 5, 6, 4, 6, 7], [0, 1, 5, 0, 5, 4], [2, 3, 7, 2, 7, 6], [1, 2, 6, 1, 6, 5], [3, 0, 4, 3, 4, 7]];
  return {
    vertices: new Float32Array(corners.flat()),
    indices: new Uint32Array(faces.flat()),
    normals: new Float32Array(0),
    colors: colors || new Float32Array(0),
    bounds: { min: [-hx, -hy, -hz], max: [hx, hy, hz] },
    has_source_colors: Boolean(colors),
    parts
  };
}

/** A stand-in mesh per visual of a payload: the primitive's size from its link facts, in millimetres. */
export function meshesFor(robot) {
  const meshes = new Map();
  for (const visual of robot.visuals) {
    if (meshes.has(visual.mesh.url)) continue;
    const fact = (robot.links.find(link => link.name === visual.link)?.visuals || [])[Number(visual.id.split(":v")[1]) - 1] || {};
    const metres = fact.type === "box" && fact.size ? fact.size
      : fact.radius ? [2 * fact.radius, 2 * fact.radius, fact.length ?? 2 * fact.radius] : [0.1, 0.1, 0.1];
    meshes.set(visual.mesh.url, boxMesh(metres.map(value => value * 1000)));
  }
  return meshes;
}

/** A payload with its once-built part list, as the robot renderer loads it. */
export function robotOf(robot, meshesByUrl = meshesFor(robot)) {
  return { robot, ...buildRobotParts(robot, meshesByUrl) };
}
