import { z } from 'zod';
import { toolCallItemSchema } from '#runtimes/acp/api/models/turns/tool-calls';

export const acpPermissionOptionSchema = z.object({
  optionId: z.string(),
  /** Human-readable label from the ACP PermissionOption.name field. */
  name: z.string(),
  /**
   * ACP-defined kind hint. Standard values: 'allow_once', 'allow_always',
   * 'reject_once', 'reject_always'. May be extended by the agent.
   */
  kind: z.union([
    z.literal('allow_once'),
    z.literal('allow_always'),
    z.literal('reject_once'),
    z.literal('reject_always'),
    z.string(),
  ]),
  /** Secondary text for the option (a question's option description). */
  description: z.string().optional(),
});
export type AcpPermissionOption = z.infer<typeof acpPermissionOptionSchema>;

export const acpPermissionRequestSchema = z.object({
  /** Stable identifier generated by the owning SessionCell for this request. */
  requestId: z.string(),
  /**
   * 'permission' asks whether the agent may act; 'question' is an agent
   * question (an ACP form elicitation) whose options are the answers.
   */
  kind: z.enum(['permission', 'question']).optional(),
  /** Display-ready snapshot of the typed tool call that triggered the request. */
  toolCall: toolCallItemSchema,
  /** What is being asked or granted: the plan, the command, the files, the question. */
  body: z.string().optional(),
  options: z.array(acpPermissionOptionSchema),
});
export type AcpPermissionRequest = z.infer<typeof acpPermissionRequestSchema>;

export const permissionDecisionSchema = z.object({
  requestId: z.string(),
  optionId: z.string(),
});
export type PermissionDecision = z.infer<typeof permissionDecisionSchema>;
