"""Nine-cylinder supercharged radial — the full, sectioned assembly.

The eighteen system models (`lib/systems.py`, in explode order) are CALLED here
and linked as occurrences; each builds in its own worker. A system joins as soon
as its `lib/<name>.py` exists. The embedded choreography (`lib/anim_js.py`,
GENERATED by `lib/animgen.py` from `lib/kin.py`) addresses parts by label.
Build through `tools/engine.py build` (it serialises assembly builds and renders).
"""

from __future__ import annotations

import importlib

from cadgen import build123d as bd
from cadgen import step

from lib.systems import ready

try:
    from lib.anim_js import ANIMATION_JS
except ImportError:  # before the first animgen run
    ANIMATION_JS = None


@step(out="../STEP/radial.step", animation=ANIMATION_JS)
def radial():
    systems = [getattr(importlib.import_module(name), name)() for name in ready()]
    if not systems:
        raise RuntimeError("no system is ready (lib/<name>.py)")
    return bd.Compound(children=systems, label="radial")


if __name__ == "__main__":
    radial()
