"""A board's manufacturing files: Gerbers and drills, the BOM, the placement file.

Each is KiCad's own export (``kicad-cli``), run on a staged copy of the board,
then made a function of the board alone: KiCad stamps creation dates into
Gerber and drill files, and those lines are removed; the Gerbers ship as one
zip whose entries are sorted and dated 1980-01-01. The same board always
writes the same bytes.

- **gerber**: every copper, mask, paste and silkscreen layer the board has plus
  the outline, the Gerber job file, and the Excellon drill files (plated and
  unplated apart), in one zip: what every fab's upload form takes.
- **bom**: one row per distinct part, read from the schematic beside the board;
  parts marked DNP are left out. JLCPCB's required columns (Comment, Designator,
  Footprint, LCSC Part #), which every other assembler accepts, then every field
  the others ask for (Quantity, MPN, Manufacturer, Description).
- **pos**: one row per placed part, in millimetres from the board's drill/place
  origin (the board script's own origin), with JLCPCB's column names
  (Designator, Mid X, Mid Y, Rotation, Layer), which the others accept. DNP
  parts are left out.

Manufacturing files are refused for a board that is not finished: one with
unrouted connections or any DRC error. That is the caller's check
(:func:`require_finished`); the BOM is exempt, since sourcing starts before
routing ends.
"""

from __future__ import annotations

import csv
import io
import re
import shutil
import tempfile
import zipfile
from pathlib import Path

__all__ = ["FAB_FORMATS", "FAB_SUFFIX", "MANUFACTURING", "export", "require_finished"]

#: The export kinds, and the file each writes beside the board by default.
FAB_SUFFIX = {"gerber": ".gerbers.zip", "bom": ".bom.csv", "pos": ".pos.csv"}
FAB_FORMATS = tuple(FAB_SUFFIX)
#: The kinds a board must be finished for.
MANUFACTURING = frozenset({"gerber", "pos"})

_DATE_LINES = re.compile(r"^(%TF\.CreationDate,.*|; #@! TF\.CreationDate,.*|G04 Created by KiCad.*|; DRILL file .*date.*|;.*Generated by.*)\r?$")
_ZIP_DATE = (1980, 1, 1, 0, 0, 0)


def _stage(board: Path, stage: Path) -> Path:
    shutil.copy2(board, stage / board.name)
    for sibling in (board.with_suffix(".kicad_pro"), board.with_suffix(".kicad_sch")):
        if sibling.is_file():
            shutil.copy2(sibling, stage / sibling.name)
    return stage / board.name


def _strip_dates(data: bytes) -> bytes:
    lines = data.decode("utf-8", errors="surrogateescape").splitlines(keepends=True)
    kept = [line for line in lines if not _DATE_LINES.match(line.rstrip("\n"))]
    return "".join(kept).encode("utf-8", errors="surrogateescape")


def _copper_layers(board_text: str) -> list[str]:
    layers = re.findall(r'\(\d+ "((?:F|B|In\d+)\.Cu)" signal', board_text)
    return list(dict.fromkeys(layers)) or ["F.Cu", "B.Cu"]


def _gerbers(board: Path, stage: Path, install) -> bytes:
    from cadgen.kicad.cli import run_kicad_cli

    layers = _copper_layers(board.read_text(encoding="utf-8")) + [
        "F.Paste", "B.Paste", "F.SilkS", "B.SilkS", "F.Mask", "B.Mask", "Edge.Cuts",
    ]
    out = stage / "gerbers"
    out.mkdir()
    run_kicad_cli(install, ["pcb", "export", "gerbers", "--output", str(out), "--layers", ",".join(layers), board.name], cwd=stage)
    run_kicad_cli(
        install,
        ["pcb", "export", "drill", "--output", str(out) + "/", "--format", "excellon", "--excellon-units", "mm",
         "--excellon-separate-th", board.name],
        cwd=stage,
    )
    files = sorted(path for path in out.iterdir() if path.is_file())
    if not any(path.suffix != ".gbrjob" for path in files):
        raise RuntimeError(f"KiCad wrote no Gerbers for {board.name}")
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for path in files:
            info = zipfile.ZipInfo(path.name, date_time=_ZIP_DATE)
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            data = _undated_job(path.read_bytes()) if path.suffix == ".gbrjob" else _strip_dates(path.read_bytes())
            archive.writestr(info, data)
    return buffer.getvalue()


def _undated_job(data: bytes) -> bytes:
    """The Gerber job file (X2's table of contents, which some fabs ask for) without its creation date."""
    import json

    job = json.loads(data.decode("utf-8"))
    job.get("Header", {}).pop("CreationDate", None)
    return (json.dumps(job, indent=2) + "\n").encode("utf-8")


def _bom(board: Path, stage: Path, install) -> bytes:
    from cadgen.kicad.cli import run_kicad_cli

    schematic = stage / board.with_suffix(".kicad_sch").name
    if not schematic.is_file():
        raise RuntimeError(f"{board.name} has no schematic beside it ({schematic.name}), which the BOM is read from")
    run_kicad_cli(
        install,
        [
            "sch", "export", "bom", "--output", "bom.csv",
            "--fields", "Value,Reference,Footprint,LCSC,${QUANTITY},MPN,Manufacturer,Description",
            "--labels", "Comment,Designator,Footprint,LCSC Part #,Quantity,MPN,Manufacturer,Description",
            "--group-by", "Value,Footprint,LCSC,MPN",
            "--sort-field", "Reference",
            "--exclude-dnp",
            schematic.name,
        ],
        cwd=stage,
    )
    return (stage / "bom.csv").read_bytes()


_POS_COLUMNS = {"Ref": "Designator", "Val": "Val", "Package": "Package", "PosX": "Mid X", "PosY": "Mid Y", "Rot": "Rotation", "Side": "Layer"}


def _pos(board: Path, stage: Path, install) -> bytes:
    from cadgen.kicad.cli import run_kicad_cli

    run_kicad_cli(
        install,
        ["pcb", "export", "pos", "--output", "pos.csv", "--format", "csv", "--units", "mm", "--side", "both",
         "--use-drill-file-origin", "--exclude-dnp", board.name],
        cwd=stage,
    )
    rows = list(csv.reader(io.StringIO((stage / "pos.csv").read_text(encoding="utf-8"))))
    if not rows:
        raise RuntimeError(f"KiCad wrote an empty placement file for {board.name}")
    header = [_POS_COLUMNS.get(column.strip(), column.strip()) for column in rows[0]]
    out = io.StringIO()
    writer = csv.writer(out, lineterminator="\n")
    writer.writerow(header)
    writer.writerows(rows[1:])
    return out.getvalue().encode("utf-8")


_EXPORTERS = {"gerber": _gerbers, "bom": _bom, "pos": _pos}


def export(fmt: str, board: Path, *, install=None) -> bytes:
    """The ``fmt`` manufacturing file of the board at ``board``, as bytes."""
    from cadgen.kicad.install import find_kicad

    if fmt not in _EXPORTERS:
        raise ValueError(f"unknown manufacturing export {fmt!r}; one of {', '.join(FAB_FORMATS)}")
    install = install or find_kicad()
    with tempfile.TemporaryDirectory(prefix=f"cadgen-pcb-{fmt}-") as folder:
        stage = Path(folder)
        staged = _stage(Path(board), stage)
        return _EXPORTERS[fmt](staged, stage, install)


def require_finished(board: Path, *, fmt: str, install=None) -> None:
    """Refuse manufacturing files for a board with unrouted connections or DRC errors."""
    from cadgen.kicad.check import check_project

    report = check_project(Path(board), install=install)
    blocking = [finding for finding in report.findings if finding.severity == "error"]
    if blocking:
        listed = "\n  ".join(finding.render() for finding in blocking[:20])
        more = f"\n  ... and {len(blocking) - 20} more" if len(blocking) > 20 else ""
        raise RuntimeError(
            f"{Path(board).name} is not finished, so no {fmt} file is written "
            f"({report.unrouted} unrouted connection(s), {len(report.errors)} error(s)):\n  {listed}{more}"
        )
