"""A KiCad board or schematic as the picture the CAD Viewer and ``cadgen pcb snapshot`` draw.

KiCad draws it: ``kicad-cli`` plots the document to SVG, and the payload carries
those SVGs unchanged (but for the timestamped ``<title>`` KiCad stamps on
them). Nothing here re-implements KiCad's plotter -- not zones, not stroke-font
text, not pad shapes -- so what the viewer shows is what KiCad shows.

A board is one picture: its layers stacked back to front (bottom silkscreen
and fabrication, bottom copper, inner copper deepest first, top copper, top
silkscreen and fabrication, the outline), on KiCad's board background. A board
with unrouted connections also gets its ratsnest: the DRC's unconnected pairs
drawn as lines on a scratch layer of the staged copy (``Dwgs.User``, cleared
first), so KiCad plots them in its own coordinates and a draft never looks
finished.

A schematic is one picture per sheet, the root first.

Everything runs on a staged copy (``kicad-cli`` writes beside what it reads).
The payload is derived data: cached in the store's ``drawing`` index, keyed by
the document's bytes (a schematic's: every sheet beside it), this module's
scheme and the KiCad version.
"""

from __future__ import annotations

import hashlib
import json
import re
import shutil
import tempfile
from pathlib import Path

from cadgen.kicad import sexpr
from cadgen.kicad.sexpr import Sym

__all__ = [
    "BOARD_BACKGROUND",
    "PLOT_SCHEMA_VERSION",
    "PlotError",
    "SCHEMATIC_BACKGROUND",
    "build_plot",
    "plot_payload_bytes",
]

PLOT_SCHEMA_VERSION = 1
#: KiCad's default colour theme behind a board, and behind a schematic sheet.
BOARD_BACKGROUND = "#001023"
SCHEMATIC_BACKGROUND = "#F5F4EF"
_RATSNEST_LAYER = "Dwgs.User"
_RATSNEST_WIDTH = 0.1
_SUFFIXES = (".kicad_pcb", ".kicad_sch")


class PlotError(ValueError):
    """A document KiCad could not plot, with the reason. A ``ValueError``: the
    viewer's GET funnel answers it as a 400 with this message."""


def _strip_stamps(svg: str) -> str:
    # KiCad stamps the plot time into <title>; the picture must be a function of the document.
    svg = re.sub(r"<title>.*?</title>", "", svg, count=1, flags=re.DOTALL)
    return re.sub(r"<desc>Image generated by [^<]*</desc>", "", svg, count=1)


def _svg_size(svg: str) -> tuple[float, float]:
    match = re.search(r'viewBox="\s*([-\d.]+)\s+([-\d.]+)\s+([-\d.]+)\s+([-\d.]+)\s*"', svg)
    if match is None:
        raise PlotError("KiCad's plot has no viewBox")
    return round(float(match.group(3)), 4), round(float(match.group(4)), 4)


def _copper_order(board: list) -> list[str]:
    """The board's copper layers, back to front."""
    layers = sexpr.find(board, "layers")
    copper: list[str] = []
    for entry in (layers[1:] if layers is not None else []):
        if isinstance(entry, list) and len(entry) >= 3 and str(entry[1]).endswith(".Cu"):
            copper.append(str(entry[1]))
    inner = sorted(
        (name for name in copper if name.startswith("In")),
        key=lambda name: int(re.sub(r"\D", "", name) or 0),
        reverse=True,
    )
    order = []
    if "B.Cu" in copper:
        order.append("B.Cu")
    order.extend(inner)
    if "F.Cu" in copper:
        order.append("F.Cu")
    return order or ["B.Cu", "F.Cu"]


def _clear_layer(node: list, layer: str) -> list:
    """``node`` without any item drawn on ``layer`` (footprint children included)."""
    kept: list = [node[0]]
    for child in node[1:]:
        if isinstance(child, list) and child and sexpr.value(child, "layer") == layer and str(child[0]).startswith(("gr_", "fp_")):
            continue
        if isinstance(child, list) and child and child[0] == "footprint":
            child = _clear_layer(child, layer)
        kept.append(child)
    return kept


def _board_payload(path: Path, install) -> dict:
    from cadgen.kicad.cli import drc_findings, run_kicad_cli

    text = path.read_text(encoding="utf-8")
    try:
        tree = sexpr.parse(text)
    except sexpr.SexprError as error:
        raise PlotError(f"{path.name} is not a readable KiCad board ({error})") from None
    if sexpr.head(tree) != "kicad_pcb":
        raise PlotError(f"{path.name} is not a KiCad board")
    with tempfile.TemporaryDirectory(prefix="cadgen-kicad-plot-") as folder:
        stage = Path(folder)
        staged = stage / path.name
        staged.write_text(text, encoding="utf-8")
        project = path.with_suffix(".kicad_pro")
        if project.is_file():
            shutil.copy2(project, stage / project.name)
        # The DRC is asked for one thing: what is still unconnected.
        run_kicad_cli(install, ["pcb", "drc", "--format", "json", "-o", "drc.json", path.name], cwd=stage)
        unconnected = [finding for finding in drc_findings(stage / "drc.json", to_script=lambda x, y: (x, y)) if finding.check == "unconnected"]
        layers = ["B.Fab", "B.SilkS", *_copper_order(tree), "F.SilkS", "F.Fab", "Edge.Cuts"]
        if unconnected:
            marked = _clear_layer(tree, _RATSNEST_LAYER)
            for index, finding in enumerate(unconnected):
                points = [position for _text, position in finding.items if position is not None]
                if len(points) < 2:
                    continue
                (x1, y1), (x2, y2) = points[0], points[1]
                marked.insert(
                    len(marked) - 1,
                    [
                        Sym("gr_line"),
                        [Sym("start"), x1, y1],
                        [Sym("end"), x2, y2],
                        [Sym("stroke"), [Sym("width"), _RATSNEST_WIDTH], [Sym("type"), Sym("solid")]],
                        [Sym("layer"), _RATSNEST_LAYER],
                        [Sym("uuid"), f"00000000-0000-4000-8000-{index:012d}"],
                    ],
                )
            staged.write_text(sexpr.dumps(marked), encoding="utf-8")
            layers.append(_RATSNEST_LAYER)
        run_kicad_cli(
            install,
            [
                "pcb", "export", "svg", "--mode-single", "--fit-page-to-board", "--exclude-drawing-sheet",
                "--layers", ",".join(layers), "-o", "board.svg", path.name,
            ],
            cwd=stage,
        )
        svg = _strip_stamps((stage / "board.svg").read_text(encoding="utf-8"))
    width, height = _svg_size(svg)
    return {
        "kind": "board",
        "sheets": [{"name": path.stem, "svg": svg, "width": width, "height": height, "background": BOARD_BACKGROUND}],
        "unrouted": len(unconnected),
    }


def _schematic_files(path: Path) -> list[Path]:
    return sorted(candidate for candidate in path.parent.glob("*.kicad_sch") if candidate.is_file())


def _schematic_payload(path: Path, install) -> dict:
    from cadgen.kicad.cli import run_kicad_cli

    head = path.read_text(encoding="utf-8")[:200]
    if not head.lstrip().startswith("(kicad_sch"):
        raise PlotError(f"{path.name} is not a KiCad schematic")
    with tempfile.TemporaryDirectory(prefix="cadgen-kicad-plot-") as folder:
        stage = Path(folder)
        for sheet in _schematic_files(path):
            shutil.copy2(sheet, stage / sheet.name)
        for extra in (path.with_suffix(".kicad_pro"), path.parent / "sym-lib-table"):
            if extra.is_file():
                shutil.copy2(extra, stage / extra.name)
        run_kicad_cli(install, ["sch", "export", "svg", "-o", "plots", path.name], cwd=stage)
        plots = sorted((stage / "plots").glob("*.svg"))
        if not plots:
            raise PlotError(f"KiCad drew no sheet of {path.name}")
        root = stage / "plots" / f"{path.stem}.svg"
        ordered = ([root] if root in plots else []) + [plot for plot in plots if plot != root]
        sheets = []
        for plot in ordered:
            svg = _strip_stamps(plot.read_text(encoding="utf-8"))
            width, height = _svg_size(svg)
            name = plot.stem[len(path.stem) + 1 :] if plot.stem.startswith(path.stem + "-") else plot.stem
            sheets.append({"name": name or path.stem, "svg": svg, "width": width, "height": height, "background": SCHEMATIC_BACKGROUND})
    return {"kind": "schematic", "sheets": sheets, "unrouted": None}


def build_plot(path: Path, *, install=None) -> dict:
    """The plot payload of the board or schematic at ``path``."""
    from cadgen.kicad.install import find_kicad

    path = Path(path).resolve()
    suffix = path.suffix.lower()
    if suffix not in _SUFFIXES:
        raise PlotError(f"{path.name} is not a KiCad board (.kicad_pcb) or schematic (.kicad_sch)")
    if not path.is_file():
        raise PlotError(f"{path.name} does not exist")
    install = install or find_kicad()
    payload = _board_payload(path, install) if suffix == ".kicad_pcb" else _schematic_payload(path, install)
    return {"schemaVersion": PLOT_SCHEMA_VERSION, "kicadVersion": install.version, **payload}


def _document_hash(path: Path) -> str:
    digest = hashlib.sha256()
    files = [path] if path.suffix.lower() == ".kicad_pcb" else _schematic_files(path)
    for entry in files:
        digest.update(entry.name.encode("utf-8") + b"\0")
        digest.update(hashlib.sha256(entry.read_bytes()).digest())
    return digest.hexdigest()


def plot_payload_bytes(path: Path) -> bytes:
    """The payload as JSON bytes, from the store when these bytes were plotted before."""
    from cadgen.kicad.install import find_kicad
    from cadgen.store import drawings

    path = Path(path).resolve()
    if path.suffix.lower() not in _SUFFIXES:
        raise PlotError(f"{path.name} is not a KiCad board (.kicad_pcb) or schematic (.kicad_sch)")
    if not path.is_file():
        raise PlotError(f"{path.name} does not exist")
    install = find_kicad()
    scheme = f"kicad-plot:{PLOT_SCHEMA_VERSION}:{install.version}"
    key = drawings.drawing_input_key(_document_hash(path), scheme=scheme)
    cached = drawings.read(key)
    if cached is not None:
        return cached
    data = json.dumps(build_plot(path, install=install), separators=(",", ":")).encode("utf-8")
    drawings.write(key, data)
    return data
