#!/usr/bin/env bash
# Start the CAD Viewer the way the shipped skill tells a user to, and check it answers.
#
# Every other check asks whether the distribution is correctly ASSEMBLED. bundle.sh --check
# compares generated bytes, check-builds.sh inspects the layout. None of them RUN it.
# `npm start` was declared in the runtime's package.json, shipped without its launcher,
# and stayed broken from 0.4.0 to 0.4.18 because no test ever executed the one command the
# skill documents.
#
# The command below is that command: `cadgen viewer --host 127.0.0.1 --json --detach`, spelled
# `python -m cadgen.viewer` so the interpreter is explicit. Keep it identical to the one
# in skills/cad/SKILL.md; keep its launch options aligned with this test. One addition:
# `--port` with a port nobody holds, because the default (3245) is the developer's own
# viewer on a workstation, and a launch there would reuse it -- or, running other code,
# replace it. The URL is still read from the --json line, exactly as an agent does. It
# serves the client the WHEEL ships -- cadgen/_runtime/viewer, written by
# scripts/bundle/bundle.sh -- pinned through CADGEN_VIEWER_DIST so a checkout's own
# apps/web/dist cannot stand in for it. Run bundle.sh first, exactly as test.yml does.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

HOST="127.0.0.1"
# VIEWER_RUNTIME_DIR points the smoke test at a client bundled somewhere else
# (CADGEN_RUNTIME_CHECK_DIR-style scratch builds). CI uses the default.
RUNTIME="${VIEWER_RUNTIME_DIR:-$REPO_ROOT/packages/cadgen/src/cadgen/_runtime/viewer}"

echo "==> CAD Viewer launch smoke test (\$PYTHON -m cadgen.viewer)"

# The built client has to be IN the wheel's runtime: its absence is the exact regression
# this guards, and it surfaces as a served page that is 404 rather than as a bad server.
if [ ! -f "$RUNTIME/index.html" ]; then
  echo "FAIL: no bundled CAD Viewer client at $RUNTIME (index.html missing)" >&2
  echo "      Run scripts/bundle/bundle.sh first (test.yml bundles before this step)." >&2
  exit 1
fi
export CADGEN_VIEWER_DIST="$RUNTIME"

log="$(mktemp)"
serve_root="$(mktemp -d)"
# This is the interpreter that plays the role of "the one the CAD skill's
# launch command runs" -- the server is a module of that cadgen.
#
# Resolution FALLS BACK instead of demanding a repo venv, because there are two
# venv-less callers and both are ordinary:
#
#   * GitHub Actions. .github/actions/setup-deps uses actions/setup-python and
#     installs requirements-dev.txt into the interpreter on PATH; no .venv is
#     ever created. Hard-requiring $REPO_ROOT/.venv/bin/python made this step
#     fail before it started anything, on every pull request.
#   * A lightweight worktree. CONTRIBUTING's recipe deliberately does not copy
#     .venv, so a developer running this by hand hit the identical wall.
#
# Setting VIEWER_PYTHON in test.yml would have fixed only the first. The
# fallback fixes both, and uses the same order scripts/test/common.sh already
# uses for every other Python runner in this repo, so "which interpreter do the
# tests use" has one answer.
#
# The first candidate that can import cadgen wins, and cadgen is REQUIRED: the
# end-to-end import below is most of what this script proves, so a machine that
# cannot run it should say so here in one line rather than 60 seconds later
# inside a POST that returns ok:false. An explicit VIEWER_PYTHON is never
# second-guessed — it is used, or the script fails naming it.
pick_interpreter() {
  local candidates=()
  if [ -n "${VIEWER_PYTHON:-}" ]; then
    candidates=("$VIEWER_PYTHON")
  else
    candidates=(
      "$REPO_ROOT/.venv/bin/python"
      "$REPO_ROOT/.venv/Scripts/python.exe"
      python3
      python
    )
  fi

  local candidate resolved
  FOUND_INTERPRETER=""
  for candidate in "${candidates[@]}"; do
    resolved="$(command -v "$candidate" 2>/dev/null || true)"
    [ -n "$resolved" ] && [ -x "$resolved" ] || continue
    [ -n "$FOUND_INTERPRETER" ] || FOUND_INTERPRETER="$resolved"
    if "$resolved" -c 'import importlib.util, sys; sys.exit(0 if importlib.util.find_spec("cadgen") else 1)' \
        >/dev/null 2>&1; then
      PYTHON="$resolved"
      return 0
    fi
  done
  return 1
}

if ! pick_interpreter; then
  if [ -n "${VIEWER_PYTHON:-}" ]; then
    echo "FAIL: VIEWER_PYTHON=$VIEWER_PYTHON cannot run, or cannot import cadgen." >&2
  elif [ -z "$FOUND_INTERPRETER" ]; then
    echo "FAIL: no Python interpreter found (tried the repo venv, python3, and python)." >&2
    echo "      Set VIEWER_PYTHON to the one that installed requirements-dev.txt." >&2
    exit 1
  else
    echo "FAIL: cadgen is not importable from $FOUND_INTERPRETER." >&2
  fi
  echo "      This test imports a real STEP end to end, so the launching interpreter" >&2
  echo "      needs cadgen: pip install -r requirements-dev.txt, or set VIEWER_PYTHON." >&2
  exit 1
fi
echo "    interpreter: $PYTHON"
# Cold: a smoke test spawns no build daemon.
export CADGEN_DAEMON=0
unset CADGEN_BROKER CADGEN_BROKER_KEY CADGEN_BROKER_STATS CADGEN_ROOT_ID
# Isolated store: content keying would otherwise resolve the fixture against
# the developer's real cache and skip the import this smoke test exists to run.
export CADGEN_CACHE_DIR="$(mktemp -d)"
# A private state directory (the detached viewer's log, the analytics answer) and
# temporary directory: nothing here touches the developer's own.
private_tmp="$("$PYTHON" -c 'import tempfile; print(tempfile.mkdtemp(prefix="cv-"))')"
export TMPDIR="$private_tmp" TEMP="$private_tmp" TMP="$private_tmp"
export CADGEN_STATE_DIR="$private_tmp/state"
export CADGEN_DAEMON_STATE_DIR="$private_tmp/daemon"
PORT="$("$PYTHON" -c 'import socket; s = socket.socket(); s.bind(("127.0.0.1", 0)); print(s.getsockname()[1]); s.close()')"
STARTED=""
cleanup() {
  if [ -n "$STARTED" ]; then
    "$PYTHON" -m cadgen.viewer stop --port "$PORT" >/dev/null 2>&1 || true
  fi
  rm -rf "$serve_root" "$CADGEN_CACHE_DIR" "$private_tmp"
  rm -f "$log"
}
trap cleanup EXIT

# A file is named by its absolute path, so the folder a launch runs in only decides
# where a developer's relative links resolve. --detach makes the command RETURN once
# the server announces itself: the server keeps running in the background, writing
# to the viewer log in the state directory, and $log holds only what the launcher
# itself said. A launcher that never returned would hang here rather than fail, so
# the documented command is bounded where the platform can bound it.
bounded=()
if command -v timeout >/dev/null 2>&1; then
  bounded=(timeout 120)
fi
if ! launch_json="$(cd "$serve_root" && ${bounded[@]+"${bounded[@]}"} "$PYTHON" -m cadgen.viewer --host "$HOST" --port "$PORT" --json --detach 2>"$log")"; then
  echo "FAIL: the detached launch did not return success" >&2
  sed 's/^/    /' "$log" >&2
  exit 1
fi

# The {url,port,action} JSON line is the whole of stdout under --json.
if ! printf '%s' "$launch_json" | grep -q "^{\"url\":\"http://$HOST:$PORT/\",\"port\":$PORT,\"action\":\"started\"}\$"; then
  echo "FAIL: no {url,port,action:started} JSON line on stdout: $launch_json" >&2
  sed 's/^/    /' "$log" >&2
  exit 1
fi
STARTED=1
# What the detached server itself writes, for the failure messages below.
server_log() {
  cat "$CADGEN_STATE_DIR/viewer.log" 2>/dev/null || true
}

# The launcher writes the {url,port,action} line only after the socket is bound and
# listening with the app attached (pinned by tests/python/packages/cadgen/viewer/test_launcher.py
# AnnounceIsConnectable: first request, no retry, 1s budget), so the FIRST request after
# reading it answers 200. The two extra attempts are slack for a starved CI runner, not
# cover for the launcher — a miss is printed so it cannot pass silently, and a launcher
# that needed the retry fails the unit pin first.
status=""
attempt=0
for _ in $(seq 1 3); do
  attempt=$((attempt + 1))
  status="$(curl -s -o /dev/null -m 3 -w '%{http_code}' "http://$HOST:$PORT/" || true)"
  [ "$status" = "200" ] && break
  echo "    warning: request $attempt after the announce returned ${status:-none}; retrying" >&2
  sleep 1
done
if [ "$status" != "200" ]; then
  echo "FAIL: no 200 from http://$HOST:$PORT/ within $attempt requests (last status: ${status:-none})" >&2
  server_log | sed 's/^/    /' >&2
  exit 1
fi

# The front end alone is not proof: the server serves a prebuilt bundle, so a live page with
# a dead CAD API still looks fine in a browser until the first model load.
api="$(curl -s -o /dev/null -m 3 -w '%{http_code}' "http://$HOST:$PORT/__cad/server" || true)"
if [ "$api" != "200" ]; then
  echo "FAIL: the page served but /__cad/server returned ${api:-none}" >&2
  server_log | sed 's/^/    /' >&2
  exit 1
fi

# Launch idempotence: relaunching at the same version -- from ANOTHER folder, since one
# viewer serves every file -- must REUSE the running viewer (same port, action:"reused"),
# not spawn a second instance.
reuse_json="$(cd "$private_tmp" && "$PYTHON" -m cadgen.viewer --host "$HOST" --port "$PORT" --json --detach)"
if ! printf '%s' "$reuse_json" | grep -q '"action":"reused"'; then
  echo "FAIL: relaunching did not reuse the running viewer: $reuse_json" >&2
  exit 1
fi
if ! printf '%s' "$reuse_json" | grep -q "\"port\":$PORT"; then
  echo "FAIL: reuse reported a different port than the running viewer: $reuse_json" >&2
  exit 1
fi

# End-to-end display FROM THE BUNDLE: a raw STEP, named by its absolute path, goes
# not-compiled -> POST (cadgen's compile entry point, a job in the pool)
# -> compiled geometry -> a real browser load that derives and fetches its
# display surface. Its small STEP fixture belongs to this test rather than the
# repository's shared model workspace. Geometry completion and display readiness
# are separate contracts: the artifact endpoint must stay "compiled" after the
# geometry tree lands, while
# the bundled client drives missing SURF work through /__cad/surfaces.
FIXTURE="$REPO_ROOT/tests/fixtures/cad/import-smoke.step"
if ! head -1 "$FIXTURE" | grep -q "ISO-10303-21"; then
  echo "FAIL: import fixture is not STEP text: $FIXTURE" >&2
  exit 1
fi
cp "$FIXTURE" "$serve_root/smoke.step"
smoke_ref="$("$PYTHON" -c 'import sys, urllib.parse; print(urllib.parse.quote(sys.argv[1], safe=""))' "$serve_root/smoke.step")"
if [ "$(curl -s -o /dev/null -m 10 -w '%{http_code}' "http://$HOST:$PORT/__cad/artifact?file=smoke.step")" != "400" ]; then
  echo "FAIL: a relative ?file= was not refused (400)" >&2
  exit 1
fi
step_url="http://$HOST:$PORT/__cad/artifact?file=$smoke_ref"
status_json="$(curl -s -m 10 "$step_url")"
if ! printf '%s' "$status_json" | grep -q '"not-compiled"'; then
  echo "FAIL: raw STEP did not report not-compiled: $status_json" >&2
  exit 1
fi
if ! printf '%s' "$status_json" | grep -q '"compile":true'; then
  echo "FAIL: raw STEP status did not offer the compile: $status_json" >&2
  exit 1
fi
# The POST starts the compile and answers at once; the status route says when it
# has landed. The compile pays one cold interpreter + OCP start, so the wait for
# that is bounded generously.
build_json="$(curl -s -m 30 -X POST -H 'x-cadgen-viewer: 1' "$step_url")"
if ! printf '%s' "$build_json" | grep -q '"ok":true'; then
  echo "FAIL: the compile did not start: $build_json" >&2
  exit 1
fi
compile_deadline=$((SECONDS + 120))
status_json="$(curl -s -m 10 "$step_url")"
until printf '%s' "$status_json" | grep -q '"state":"compiled"'; do
  if printf '%s' "$status_json" | grep -q '"state":"failed"'; then
    echo "FAIL: the compile failed: $status_json" >&2
    exit 1
  fi
  if [ "$SECONDS" -ge "$compile_deadline" ]; then
    echo "FAIL: compiled STEP did not settle compiled: $status_json" >&2
    exit 1
  fi
  sleep 0.5
  status_json="$(curl -s -m 10 "$step_url")"
done
# The tree lands in the (isolated) store, keyed by the document's bytes.
if ! ls "$CADGEN_CACHE_DIR"/index/document/* > /dev/null 2>&1; then
  echo "FAIL: compile reported compiled but the store indexes no document" >&2
  exit 1
fi
catalog_json="$(curl -s -m 10 "http://$HOST:$PORT/__cad/catalog?file=$smoke_ref")"
if ! printf '%s' "$catalog_json" | grep -q '"url":"/__cad/store?file='; then
  echo "FAIL: the compiled STEP's catalog row did not name its immutable tree: $catalog_json" >&2
  exit 1
fi

# Loading the page is load-bearing. Merely accepting the new compiled state
# would let this smoke pass with a dead display path: a cold isolated store has
# no SURF or mesh entries, so the bundled client must request exact surface
# derivation, fetch the pinned SURF bytes, tessellate them, and clear its loading
# overlay. CI installs Playwright's Chromium with requirements-dev.txt.
"$PYTHON" - "http://$HOST:$PORT/?file=$smoke_ref" "$(cat "$REPO_ROOT/VERSION")" <<'PY'
import sys
import time
from urllib.parse import parse_qs, urlparse

from playwright.sync_api import sync_playwright

url = sys.argv[1]
responses = []
page_errors = []
surface_payload = None
surface_fetches = set()

with sync_playwright() as playwright:
    browser = playwright.chromium.launch(
        headless=True,
        args=["--use-angle=swiftshader", "--enable-unsafe-swiftshader", "--ignore-gpu-blocklist"],
    )
    try:
        page = browser.new_page(viewport={"width": 1000, "height": 720})
        # The startup update check must not depend on GitHub or its rate limit.
        page.route(
            "https://api.github.com/repos/earthtojake/text-to-cad/releases/latest",
            lambda route: route.fulfill(json={"tag_name": f"v{sys.argv[2]}"}),
        )
        page.on("response", lambda response: responses.append(response))
        page.on("pageerror", lambda error: page_errors.append(str(error)))
        page.goto(url, wait_until="domcontentloaded", timeout=30_000)

        seen = 0
        deadline = time.monotonic() + 120
        while time.monotonic() < deadline:
            page.wait_for_timeout(100)
            current = responses[seen:]
            seen = len(responses)
            for response in current:
                request = response.request
                parsed = urlparse(response.url)
                if parsed.path == "/__cad/surfaces" and request.method == "POST" and response.ok:
                    payload = response.json()
                    components = payload.get("components") if isinstance(payload, dict) else None
                    if components and all(row.get("state") == "ready" for row in components.values()):
                        surface_payload = payload
                elif parsed.path == "/__cad/store" and response.ok:
                    query = parse_qs(parsed.query)
                    if query.get("tree") and query.get("surfaceInput") and query.get("object"):
                        surface_fetches.add(response.url)

            overlay_gone = page.locator(".cad-loading-overlay").count() == 0
            if surface_payload and surface_fetches and overlay_gone:
                break

        if page_errors:
            raise RuntimeError("browser page error: " + " | ".join(page_errors))
        if not surface_payload:
            raise RuntimeError("bundled client did not complete a cold /__cad/surfaces request")
        rows = surface_payload["components"]
        missing = [
            cid for cid, row in rows.items()
            if not any(fetch.endswith(row["url"]) for fetch in surface_fetches)
        ]
        if missing:
            raise RuntimeError("bundled client did not fetch pinned SURF bytes for: " + ", ".join(missing))
        if page.locator(".cad-loading-overlay").count():
            raise RuntimeError("bundled client did not finish tessellating the display surface")
        canvases = page.locator("canvas")
        if not canvases.count() or not any(canvases.nth(index).is_visible() for index in range(canvases.count())):
            raise RuntimeError("bundled client completed surface work without a visible canvas")
        alerts = [text.strip() for text in page.locator('[role="alert"]').all_text_contents() if text.strip()]
        if alerts:
            raise RuntimeError("bundled client reported an alert: " + " | ".join(alerts))
        print(f"    bundled client displayed {len(rows)} cold-derived surface component(s)")
    finally:
        browser.close()
PY

# The other verb of the same entrypoint: stop must end it, and free its port.
if ! "$PYTHON" -m cadgen.viewer stop --port "$PORT" | grep -q "Stopped CAD Viewer on port $PORT"; then
  echo "FAIL: 'cadgen viewer stop --port $PORT' did not stop the viewer" >&2
  exit 1
fi
STARTED=""
if curl -s -o /dev/null -m 3 "http://$HOST:$PORT/__cad/server"; then
  echo "FAIL: port $PORT still answers after 'cadgen viewer stop'" >&2
  exit 1
fi

echo "    served / and /__cad/server on port $PORT; cadgen step compile + bundled display e2e OK; reuse/stop OK"
echo "==> CAD Viewer launch smoke test passed"
